Implement formula update from Homebrew repository

diff --git a/tools/update-formulae b/tools/update-formulae
--- a/tools/update-formulae
+++ b/tools/update-formulae
@@ -191,5 +191,74 @@ else
   exit 0
 fi
 
-# TODO: Implement 'update' action.
-die "Sorry, update not yet implemented."
+# Update formulae, i.e. check Homebrew repository for changes after recorded
+# commit ID, extract old and new version, provide diff and log and alter
+# versions file to reflect upcoming changes.
+num_updated=0
+old_meta=("${new_meta[@]}")
+new_meta=()
+echo
+echo "Updating versions file and formulae from Homebrew repository:"
+for info in "${old_meta[@]}" ; do
+  # Parse the info line (w/o checks since we just generated these lines).
+  chunks=(${info})
+  formula_name="${chunks[0]}"
+  formula_base="${chunks[1]#base=}"
+  old_id="${chunks[2]#commit=}"
+  old_date="${chunks[3]#date=}"
+
+  # Query Homebrew repository for most recent commit ID/date prior to 'master'.
+  git_args=(
+    -C "${homebrew_prefix}"
+    log -1 --format=%H@%aI
+    master
+    -- "Library/Formula/${formula_base}.rb"
+  )
+  commit_info="$(git "${git_args[@]}")"
+  [[ "${?}" -eq 0 && -n "${commit_info}" ]] \
+    || die "Failed to query history of formula '${formula_base}'."
+  new_id="${commit_info%%@*}"
+  new_date="${commit_info#*@}"
+
+  # Reassemble info line.
+  info_prefix="${info% commit=*}"
+  new_meta+=("${info_prefix} commit=${new_id} date=${new_date}")
+
+  # Check if there are changes and otherwise skip to next entry.
+  if [[ "${old_id}" != "${new_id}" ]] ; then
+    let ++num_updated
+    echo "  * ${formula_name}"
+  else
+    continue
+  fi
+
+  # Add comment about pending change to our own formula and generate files that
+  # allow to reconstruct and adapt the change.
+  cat >> "${formula_dir}/${formula_name}.rb" <<EOF
+
+# Base Homebrew formula '${formula_base}' has changed:
+#   * Old commit: ${old_id} (${old_date})
+#   * New commit: ${new_id} (${new_date})
+#   * See '${formula_name}.{OLD,NEW,DIFF,LOG}' for details, incorporate those
+#     changes, if applicable, and remove this comment afterwards.
+EOF
+  git -C "${homebrew_prefix}" \
+    show "${old_id}:Library/Formula/${formula_base}.rb" \
+    > "${formula_dir}/${formula_name}.OLD"
+  git -C "${homebrew_prefix}" \
+    show "${new_id}:Library/Formula/${formula_base}.rb" \
+    > "${formula_dir}/${formula_name}.NEW"
+  git -C "${homebrew_prefix}" \
+    diff "${old_id}..${new_id}" -- "Library/Formula/${formula_base}.rb" \
+    > "${formula_dir}/${formula_name}.DIFF"
+  git -C "${homebrew_prefix}" \
+    log -p "${old_id}..${new_id}" -- "Library/Formula/${formula_base}.rb" \
+    > "${formula_dir}/${formula_name}.LOG"
+done
+if [[ "${num_updated}" -eq 0 ]] ; then
+  echo "  (all entries already up-to-date)"
+else
+  echo
+  echo "Writing versions file with ${num_updated} updated entries."
+  printf "%s\n" "${new_meta[@]}" > "${versions_path}"
+fi
